#!/usr/bin/env python

import rospy
from crazyflie_driver.msg import Position
from tf.transformations import quaternion_from_euler
from a_star import *
from path2map import *
from nav_msgs.msg import Path
from geometry_msgs.msg import PoseStamped

path_world = "/home/maciejw/dd2419_ws/src/course_packages/dd2419_resources/worlds_json/saal3.world.json"



def exe_path(start,end):
    '''
    start: start point on map
    end: goal point on map
    '''
    pathyaw=[]
    pathz=[]
    pathx, pathy = find_path(start, end, path_world)
    pub_cmd = rospy.Publisher('/cf1/cmd_position', Position, queue_size=2)
    rate = rospy.Rate(10)
    for i in range(len(pathx)):
        pathz[i]=0.3
        pathyaw[i]=45*i 
        cmd = Position()
        cmd.header.stamp = rospy.Time.now()
        cmd.header.frame_id = 'map' # a simple random number
        cmd.x = pathx[i]
        cmd.y = pathy[i]
        cmd.z = pathz[i]
        cmd.yaw = pathyaw[i]
        pub_cmd.publish(cmd)
        rate.sleep()



rospy.init_node('exe_path', anonymous=True)
rate = rospy.Rate(10)

if __name__ == '__main__':
    start = [0.3, 0.15]
    end = [1.1, 0.15]
    while not rospy.is_shutdown():
        try:
            px,py = exe_path(start,end)
        except rospy.ROSInterruptException:
            pass
        rate.sleep()